# Generated by Django 5.2.4 on 2025-09-11 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_state_shippingaddress_shipping_addy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # حذف فیلدهای قدیمی
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_addy',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_old_cart',
        ),

        # اضافه کردن فیلدهای جدید
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_address1',
            field=models.CharField(default=' ', max_length=255, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_city',
            field=models.CharField(default='', max_length=100, verbose_name='شهر'),
        ),

        # تغییرات فیلدهای موجود
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_country',
            field=models.CharField(max_length=100, verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_full_name',
            field=models.CharField(max_length=200, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_phone',
            field=models.CharField(max_length=20, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_state',
            field=models.CharField(max_length=100, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_zipcode',
            field=models.CharField(max_length=20, verbose_name='کد پستی'),
        ),

        # اصلاح فیلد ForeignKey user
        migrations.AlterField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(
                null=True,             # اجازه می‌دهد فیلد خالی باشد
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
