# Generated by Django 5.2.4 on 2025-10-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
