# Generated by Django 5.2.4 on 2025-10-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_remove_order_status_alter_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'در انتظار پرداخت'), ('Processing', 'در حال پردازش'), ('Shipped', 'ارسال شده'), ('Delivered', 'تحویل داده شده'), ('Cancelled', 'لغو شده')], default='Pending', max_length=20),
        ),
    ]
